# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('revenue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EggsBabies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_found', models.DateField()),
                ('date_incubated', models.DateField()),
                ('description', models.CharField(max_length=2048, null=True)),
                ('is_hatched', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodReserves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('more_info', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='OstrichBreeders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('birth_year', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, 'female'), (2, 'male')])),
                ('description', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SoldBirds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('avg_weight', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='eggsbabies',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father', to='ostrich_app.OstrichBreeders'),
        ),
        migrations.AddField(
            model_name='eggsbabies',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='ostrich_app.OstrichBreeders'),
        ),
    ]
