# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ostrichbreeders',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
