# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich_app', '0002_ostrichbreeders_is_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsbabies',
            name='sex',
            field=models.IntegerField(choices=[(1, 'female'), (2, 'male')], null=True),
        ),
    ]
