# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostrich_app', '0003_eggsbabies_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsbabies',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ostrichbreeders',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
